### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by Nick-Harvey** [openshift/openshift-ansible-contrib#265]
When running the following: 

```
./ose-on-aws.py --stack-name=dev --create-key=yes --rhsm-user=rhn-support-niharvey  --rhsm-password=XXXX  --public-hosted-zone=“sysdeseng.com” --key-path=“/Users/Nick/.ssh/id_rsa.pub” --keypair=OSE-key  --rhsm-pool="Red Hat OpenShift Container Platform, Standard, 2-Core" --github-organization="Red-Dwarf-Mining-Company" --github-client-id=“XXXXX”  --github-client-secret=“xxxxxxx”
Configured values:
	stack_name: dev
	ami: ami-a33668b4
	region: us-east-1
	master_instance_type: m4.large
	node_instance_type: t2.medium
	app_instance_type: t2.medium
	bastion_instance_type: t2.micro
	keypair: OSE-key
	create_key: yes
	key_path: “/Users/Nick/.ssh/id_rsa.pub”
	create_vpc: yes
	vpc_id: None
	private_subnet_id1: None
	private_subnet_id2: None
	private_subnet_id3: None
	public_subnet_id1: None
	public_subnet_id2: None
	public_subnet_id3: None
	byo_bastion: no
	bastion_sg: /dev/null
	console port: 443
	deployment_type: openshift-enterprise
	public_hosted_zone: “sysdeseng.com”
	app_dns_prefix: apps
	apps_dns: apps.“sysdeseng.com”
	rhsm_user: rhn-support-niharvey
	rhsm_password: *******
	rhsm_pool: Red Hat OpenShift Container Platform, Standard, 2-Core
	containerized: False
	s3_bucket_name: dev-ocp-registry-“sysdeseng
	s3_username: dev-s3-openshift-user
	github_client_id: “XXXXXX”
	github_client_secret: “XXXXX”
	github_organization: Red-Dwarf-Mining-Company
```
I get the following: 

```
Traceback (most recent call last):
  File "./ose-on-aws.py", line 325, in <module>
    launch_refarch_env(auto_envvar_prefix='OSE_REFArch')
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./ose-on-aws.py", line 314, in launch_refarch_env
    status = os.system(command)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 153: ordinal not in range(128)
```

**Comment by cooktheryan** [comment]
Can you remove the quotes in your variable definitions except for the pool?

**Comment by Nick-Harvey** [comment]
That did it!
