### ISSUE TITLE
Resource CREATE failed: Message: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by mbruzek** [openshift/openshift-ansible-contrib#837]
# BUG REPORT INFO

While running the `openshift-ansible-contrib/playbooks/provisioning/openstack/provision.yaml` it failed and gave me the following errors:
```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_KqGEtA/ansible_module_os_stack.py", line 273, in <module>
    main()
  File "/tmp/ansible_KqGEtA/ansible_module_os_stack.py", line 258, in main
    id=stack.id)
AttributeError: 'bool' object has no attribute 'id'
```
```
stack_status          | CREATE_FAILED
stack_status_reason   | Resource CREATE failed: ResourceInError: resources.infra_nodes.resources[0].resources.server: Went to status ERROR due to "Message: 'NoneType' object is not iterable,  Code: 500"  
```

### Environment

- **Cloud provider**:  OpenStack

- **OS details** (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):  
```
        "Linux 3.10.0-757.el7.x86_64 x86_64", 
        "NAME=\"Red Hat Enterprise Linux Server\"", 
        "VERSION=\"7.4 (Maipo)\"", 
        "ID=\"rhel\"", 
        "ID_LIKE=\"fedora\"", 
        "VARIANT=\"Server\"", 
        "VARIANT_ID=\"server\"", 
        "VERSION_ID=\"7.4\"", 
        "PRETTY_NAME=\"Red Hat Enterprise Linux Server 7.4 (Maipo)\"", 
        "ANSI_COLOR=\"0;31\"", 
        "CPE_NAME=\"cpe:/o:redhat:enterprise_linux:7.4:GA:server\"", 
        "HOME_URL=\"https://www.redhat.com/\"", 
        "BUG_REPORT_URL=\"https://bugzilla.redhat.com/\"", 
        "", 
        "REDHAT_BUGZILLA_PRODUCT=\"Red Hat Enterprise Linux 7\"", 
        "REDHAT_BUGZILLA_PRODUCT_VERSION=7.4", 
        "REDHAT_SUPPORT_PRODUCT=\"Red Hat Enterprise Linux\"", 
        "REDHAT_SUPPORT_PRODUCT_VERSION=\"7.4\""
```

- **Version of Ansible** (`ansible --version`):  2.3.2.0

- **Version of Jinja** (`pip freeze | grep -i jinja`):  2.7.2

- **Version of Shade** (`pip freeze | grep -i shade`):  1.24.0

- **The openstack-ansible-contrib version (commit)** (`git rev-parse --short HEAD`):  a9830cb

**Copy of inventory files and custom variables used (please omit your secrets!)**:  

**Command used to invoke ansible**:  
`source /home/cloud-user/keystonerc; ansible-playbook -vvv openshift-ansible-contrib/playbooks/provisioning/openstack/provision.yaml 2>&1 > openstack_provision_log.txt`

**Output of ansible run**:  
https://gist.github.com/mbruzek/ac729707a83096851c50b9449d410776

**Anything else do we need to know**:  
I ran `openstack stack show scale-ci.example.com` and it tells me:
```
+-----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Field                 | Value                                                                                                                                                                   |
+-----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                    | 1f8ab646-3d77-4e14-9849-ab81821c87c4                                                                                                                                    |
| stack_name            | scale-ci.example.com                                                                                                                                                    |
| description           | OpenShift cluster                                                                                                                                                       |
| creation_time         | 2017-10-31T20:26:45Z                                                                                                                                                    |
| updated_time          | None                                                                                                                                                                    |
| stack_status          | CREATE_FAILED                                                                                                                                                           |
| stack_status_reason   | Resource CREATE failed: ResourceInError: resources.infra_nodes.resources[0].resources.server: Went to status ERROR due to "Message: 'NoneType' object is not iterable,  |
|                       | Code: 500"                                                                                                                                                              |
| parameters            | OS::project_id: 508d3035cc2b4c9f9d154302afd03ff2                                                                                                                        |
|                       | OS::stack_id: 1f8ab646-3d77-4e14-9849-ab81821c87c4                                                                                                                      |
|                       | OS::stack_name: scale-ci.example.com  
| outputs               | - description: Floating IPs of the etcds                                                                                                                                |
|                       |   output_key: etcd_floating_ips                                                                                                                                         |
|                       |   output_value: []                                                                                                                                                      |
|                       | - description: Floating IPs of the masters                                                                                                                              |
|                       |   output_key: master_floating_ips                                                                                                                                       |
|                       |   output_value:                                                                                                                                                         |
|                       |   - null                                                                                                                                                                |
|                       |   - null                                                                                                                                                                |
|                       |   - null                                                                                                                                                                |
|                       | - description: Private IPs of the DNS                                                                                                                                   |
|                       |   output_key: dns_private_ips                                                                                                                                           |
|                       |   output_value:                                                                                                                                                         |
|                       |   - 192.168.99.21                                                                                                                                                       |
|                       | - description: IPs of the etcds                                                                                                                                         |
|                       |   output_key: etcd_ips                                                                                                                                                  |
|                       |   output_value: []                                                                                                                                                      |
|                       | - description: IPs of the masters                                                                                                                                       |
|                       |   output_key: master_ips                                                                                                                                                |
|                       |   output_value:                                                                                                                                                         |
|                       |   - null                                                                                                                                                                |
|                       |   - null                                                                                                                                                                |
|                       |   - null                                                                                                                                                                |
|                       | - description: IPs of the nodes                                                                                                                                         |
|                       |   output_key: infra_ips                                                                                                                                                 |
|                       |   output_value:                                                                                                                                                         |
|                       |   - null                                                                                                                                                                |
|                       |   - null                                                                                                                                                                |
|                       |   - null                                                                                                                                                                |
|                       | - description: Name of the nodes                                                                                                                                        |
|                       |   output_key: infra_names                                                                                                                                               |
|                       |   output_value:                                                                                                                                                         |
|                       |   - infra-node-0.scale-ci.example.com                                                                                                                                   |
|                       |   - infra-node-1.scale-ci.example.com                                                                                                                                   |
|                       |   - infra-node-2.scale-ci.example.com                                                                                                                                   |
|                       | - description: Floating IPs of the DNS                                                                                                                                  |
|                       |   output_key: dns_floating_ips                                                                                                                                          |
|                       |   output_value:                                                                                                                                                         |
|                       |   - 172.21.0.129                                                                                                                                                        $
|                       | - description: Name of the nodes
|                       | - description: Name of the nodes                                                                                                                                        |
|                       |   output_key: node_names                                                                                                                                                |
|                       |   output_value:                                                                                                                                                         |
|                       |   - app-node-0.scale-ci.example.com                                                                                                                                     |
|                       |   - app-node-1.scale-ci.example.com                                                                                                                                     |
|                       | - description: Floating IPs of the nodes                                                                                                                                |
|                       |   output_key: node_floating_ips                                                                                                                                         |
|                       |   output_value:                                                                                                                                                         |
|                       |   - 172.21.0.122                                                                                                                                                        |
|                       |   - 172.21.0.117                                                                                                                                                        |
|                       | - description: Name of the DNS                                                                                                                                          |
|                       |   output_key: dns_name                                                                                                                                                  |
|                       |   output_value:                                                                                                                                                         |
|                       |   - dns-0.scale-ci.example.com                                                                                                                                          |
|                       | - description: Name of the etcds                                                                                                                                        |
|                       |   output_key: etcd_names                                                                                                                                                |
|                       |   output_value: []                                                                                                                                                      |
|                       | - description: Floating IPs of the nodes                                                                                                                                |
|                       |   output_key: infra_floating_ips                                                                                                                                        |
|                       |   output_value:                                                                                                                                                         |
|                       |   - null                                                                                                                                                                |
|                       |   - null                                                                                                                                                                |
|                       |   - null                                                                                                                                                                |
|                       | - description: IPs of the nodes                                                                                                                                         |
|                       |   output_key: node_ips                                                                                                                                                  |
|                       |   output_value:                                                                                                                                                         |
|                       |   - 192.168.99.18                                                                                                                                                       |
|                       |   - 192.168.99.13                                                                                                                                                       |
|                       | - description: Name of the masters                                                                                                                                      |
|                       |   output_key: master_names                                                                                                                                              |
|                       |   output_value:                                                                                                                                                         |
|                       |   - master-0.scale-ci.example.com                                                                                                                                       |
|                       |   - master-1.scale-ci.example.com                                                                                                                                       |
|                       |   - master-2.scale-ci.example.com                                                                                                                                       |
|                       |                                                                                                                                                                         |
| links                 | - href: http://172.21.0.10:8004/v1/508d3035cc2b4c9f9d154302afd03ff2/stacks/scale-ci.example.com/1f8ab646-3d77-4e14-9849-ab81821c87c4                                    |
|                       |   rel: self                                                                                                                                                             |
|                       |                                                                                                                                                                         |
| parent                | None                                                                                                                                                                    |
| disable_rollback      | True                                                                                                                                                                    |
| deletion_time         | None                                                                                                                                                                    |
| stack_user_project_id | 83af886bb1794caa8f040fd87a14be4c                                                                                                                                        |
| capabilities          | []                                                                                                                                                                      |
| notification_topics   | []                                                                                                                                                                      $
| stack_owner           | None                                                                                                                                                                    $
| timeout_mins          | 60                                                                                                                                                                      $
| tags                  | None                                                                                                                                                                    $
+-----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------$
```

**Comment by mbruzek** [comment]
I found an error in the heat-engine.log
https://gist.github.com/mbruzek/c6e19f48b1e71720f5284aeefdb62f82

**Comment by mbruzek** [comment]
When I patched the OpenStack controllers with https://github.com/openstack/nova/commit/9d6632a67d91fb3c5145c14ac38011e919d6d8c0, I was able to get past this issue.

A bugzilla issue was created here: https://bugzilla.redhat.com/show_bug.cgi?id=1510155

I would ask if someone on the contrib team could take a look and see if the code is doing anything with `instance_group.members` that we could avoid for versions of OpenStack that are not patched with this fix.

**Comment by tomassedovic** [comment]
Thanks for digging into this! As far as I can tell, there's not much we can do about this.

We might want to point it out in the readme or a debugging guide, though.
