### ISSUE TITLE
GCP: error with create dns zone step

### ISSUE THREAD

**Issue by gamkiller77** [openshift/openshift-ansible-contrib#922]
Is this a **BUG REPORT** or a **FEATURE REQUEST** ? (choose one):BUG REPORT

# BUG REPORT INFO

### Environment

- **Cloud provider**:  GCP

- **OS details** (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):  Red Hat Enterprise Linux Server 7.4 (Maipo)

- **Version of Ansible** (`ansible --version`):  ansible 2.4.2.0

- **Version of Jinja** (`pip freeze | grep -i jinja`):  Jinja2==2.7.2

- **Version of Shade** (`pip freeze | grep -i shade`):  NA

- **The openstack-ansible-contrib version (commit)** (`git rev-parse --short HEAD`):  1824341

**Copy of inventory files and custom variables used (please omit your secrets!)**:  
```
---
###
### Main Configuration Section for OCP on GCP reference architecture ###
###

# Prefix for every resource name deployed. You can deploy multiple clusters
# under single account with different prefixes and DNS configuration
prefix: 'ocp'

# Username and password for Red Hat Customer Portal
rhsm_user: 
rhsm_password: 
# Pool name which shall be used to register the instances
rhsm_pool: 

# Path to a RHEL image on local machine, downloaded from Red Hat Customer Portal
rhel_image_path: '~/Downloads/rhel-server-7.4-update-4-x86_64-kvm.qcow2'
# Choose to delete or retain the clean image during teardown
delete_image: false
# Choose to delete or retain the gold image during teardown
delete_gold_image: false

# Project ID and main zone settings for Google Cloud
gcloud_project: 'isvopenshift'
gcloud_zone: 'US-east1-b'

# Public DNS domain which will be configured in Google Cloud DNS
public_hosted_zone: 'gcsapp.ciscoisv.com'
# Public DNS name for the Master service
openshift_master_cluster_public_hostname: 'master.{{ public_hosted_zone }}'
# Internal DNS name for the Master service
openshift_master_cluster_hostname: 'internal-master.{{ public_hosted_zone }}'
# Domain name for the OpenShift applications
wildcard_zone: 'apps.{{ public_hosted_zone }}'

# Paths on the local file system for the certificate files. If empty, self-signed
# certificate will be generated
master_https_key_file: ''
master_https_cert_file: ''

# How many instances should be created for each group
master_instance_group_size: 3
infra_node_instance_group_size: 3
node_instance_group_size: 3

# Machine types
bastion_machine_type: g1-small
master_machine_type: n1-standard-4
infra_machine_type: n1-standard-2
node_machine_type: n1-standard-2

# OpenShift deployment type
# Use 'origin' to deploy OpenShift Origin on top of CentOS 7
openshift_deployment_type: openshift-enterprise
# Deploy OpenShift within containers instead of RPMs?
containerized: false
# OpenShift SDN selection
# options are 'redhat/openshift-ovs-multitenant', 'redhat/openshift-ovs-subnet'
os_sdn_network_plugin_name: 'redhat/openshift-ovs-multitenant'
# Deploy OpenShift Metrics
openshift_hosted_metrics_deploy: true
openshift_hosted_metrics_storage_volume_size: 20Gi
# Deploy OpenShift Logging
# Please note that ElasticSearch pod needs 8Gi of free RAM on a node, so you
# will probably need at least 'n1-standard-4' size for infra nodes. Alternatively
# for evaluation purposes, you can set 'openshift_logging_es_memory_limit'
# variable to cca 4Gi, so it fits on the 'n1-standard-2' size of infra nodes.
openshift_hosted_logging_deploy: true
openshift_logging_es_pvc_size: 100Gi
# OpenShift Identity Providers. This is Google oauth example (hosted_domain is
# optional and restricts login to users only from the specified domain)
# Any identity provider can be configured here, for documentation see
# https://docs.openshift.com/container-platform/latest/install_config/configuring_authentication.html#identity-providers-ansible
openshift_master_identity_providers:
- name: 'google'
  kind: 'GoogleIdentityProvider'
  login: true
  challenge: false
  mapping_method: 'claim'
  clientID: 
  clientSecret: 
  hostedDomain: 'example.com'
###
### Supplemental options ###
###
# Disk sizes in GB
bastion_disk_size: 20
master_boot_disk_size: 45
master_docker_disk_size: 25
infra_boot_disk_size: 25
infra_docker_disk_size: 25
infra_openshift_disk_size: 50
node_boot_disk_size: 25
node_docker_disk_size: 25
node_openshift_disk_size: 50
# Custom VPC Subnet, example value: '10.160.0.0/20'
# Default value is empty, when random subnet in form of 10.x.0.0/20 will be used
gce_vpc_custom_subnet_cidr: ''
```

**Command used to invoke ansible**:  ./ocp-on-gcp.sh -vvv

**Output of ansible run**:  

```
TASK [dns-zone : create dns zone] *****************************************************************************************************************
task path: /home/andelhie/openshift-ansible-contrib/reference-architecture/gcp/ansible/playbooks/roles/dns-zone/tasks/main.yaml:2
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/google/gcdns_zone.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: andelhie
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/andelhie/.ansible/tmp/ansible-tmp-1517354138.26-88170944977573 `" && echo ansible-tmp-1517354138.26-88170944977573="` echo /home/andelhie/.ansible/tmp/ansible-tmp-1517354138.26-88170944977573 `" ) && sleep 0'
<localhost> PUT /tmp/tmpl1xcpo TO /home/andelhie/.ansible/tmp/ansible-tmp-1517354138.26-88170944977573/gcdns_zone.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/andelhie/.ansible/tmp/ansible-tmp-1517354138.26-88170944977573/ /home/andelhie/.ansible/tmp/ansible-tmp-1517354138.26-88170944977573/gcdns_zone.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/andelhie/.ansible/tmp/ansible-tmp-1517354138.26-88170944977573/gcdns_zone.py; rm -rf "/home/andelhie/.ansible/tmp/ansible-tmp-1517354138.26-88170944977573/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_5cuY7a/ansible_module_gcdns_zone.py", line 375, in <module>
    main()
  File "/tmp/ansible_5cuY7a/ansible_module_gcdns_zone.py", line 340, in main
    zone = _get_zone(gcdns, zone_name)
  File "/tmp/ansible_5cuY7a/ansible_module_gcdns_zone.py", line 269, in _get_zone
    for zone in available_zones:
  File "/usr/lib/python2.7/site-packages/libcloud/dns/drivers/google.py", line 311, in _get_more
    **kwargs)
  File "/usr/lib/python2.7/site-packages/libcloud/dns/drivers/google.py", line 332, in _get_data
    params=params,)
  File "/usr/lib/python2.7/site-packages/libcloud/common/google.py", line 806, in request
    *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/libcloud/common/base.py", line 641, in request
    response = responseCls(**kwargs)
  File "/usr/lib/python2.7/site-packages/libcloud/common/base.py", line 163, in __init__
    self.object = self.parse_body()
  File "/usr/lib/python2.7/site-packages/libcloud/common/google.py", line 294, in parse_body
    raise GoogleBaseError(message, self.status, code)
libcloud.common.google.GoogleBaseError: {u'domain': u'global', u'message': u'Forbidden', u'reason': u'forbidden'}

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_5cuY7a/ansible_module_gcdns_zone.py\", line 375, in <module>\n    main()\n  File \"/tmp/ansible_5cuY7a/ansible_module_gcdns_zone.py\", line 340, in main\n    zone = _get_zone(gcdns, zone_name)\n  File \"/tmp/ansible_5cuY7a/ansible_module_gcdns_zone.py\", line 269, in _get_zone\n    for zone in available_zones:\n  File \"/usr/lib/python2.7/site-packages/libcloud/dns/drivers/google.py\", line 311, in _get_more\n    **kwargs)\n  File \"/usr/lib/python2.7/site-packages/libcloud/dns/drivers/google.py\", line 332, in _get_data\n    params=params,)\n  File \"/usr/lib/python2.7/site-packages/libcloud/common/google.py\", line 806, in request\n    *args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/libcloud/common/base.py\", line 641, in request\n    response = responseCls(**kwargs)\n  File \"/usr/lib/python2.7/site-packages/libcloud/common/base.py\", line 163, in __init__\n    self.object = self.parse_body()\n  File \"/usr/lib/python2.7/site-packages/libcloud/common/google.py\", line 294, in parse_body\n    raise GoogleBaseError(message, self.status, code)\nlibcloud.common.google.GoogleBaseError: {u'domain': u'global', u'message': u'Forbidden', u'reason': u'forbidden'}\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}

PLAY RECAP ****************************************************************************************************************************************
localhost                  : ok=49   changed=0    unreachable=0    failed=1
```
I can not find a solution to this problem at this point any help would be great.

Andy

**Comment by pschiffe** [comment]
Can you create a dns zone manually in a web console here https://console.cloud.google.com/net-services/dns/zones ?

**Comment by gamkiller77** [comment]
I was able to add a new zone just find.  I added the app. zone per the config.yaml file.

**Comment by gamkiller77** [comment]
Ok i cleaned up some permission and wiped the git and re pulled and I got pass this problem.

**Comment by mrdab** [comment]
I got the same error ( I can create DNS zones manually in GCP Console), anybody can elaborate on how to resolve this issue?
